# Generated by Django 5.1.2 on 2024-10-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('guessed_letters', models.CharField(default='', max_length=26)),
                ('incorrect_guesses', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('InProgress', 'InProgress'), ('Lost', 'Lost'), ('Won', 'Won')], default='InProgress', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
